Description: "Network: VPC, Subnets, RouteTables, Internet Gateway, NAT Gateways"

Metadata:
 AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Main parameters"
        Parameters:
          - Environment
          - ClientName
          - Index
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VPCBlock
          - PublicSubnet01CIDR

Parameters:
  Environment:
    Type: String
    Default: 'poc'
    Description: Environment name, i.e. prod/stg/dev/tst/poc/qa

  ClientName:
    Type: String
    Description: Client name

  Index:
    Type: String
    Default: '01'
    Description: Index

  VPCBlock:
    Type: String
    Default: '10.20.0.0/21'

  PublicSubnet01CIDR:
    Type: String
    Default: '10.20.0.0/24'
    Description: "Public Subnet-01 CIDR"

Resources:
#============= VPC ==================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  !Join ['-', [!Ref Environment, !Ref ClientName, !Ref Index, "vpc", "01" ]]
      - Key: env
        Value:  !Ref Environment
      - Key: client
        Value:  !Ref ClientName
      - Key: index
        Value:  !Ref Index
      - Key: "Description"
        Value:  !Join ['', ["Created by CloudFormation Stack ", !Ref "AWS::StackName" ]]



#====== Internet Gateway =======
  GatewayInternet:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
      - Key: Name
        Value:  !Join ['-', [!Ref Environment, !Ref ClientName, !Ref Index, "igw", "01" ]]
      - Key: env
        Value:  !Ref Environment
      - Key: client
        Value:  !Ref ClientName
      - Key: index
        Value:  !Ref Index
      - Key: "Description"
        Value:  !Join ['', ["Created by CloudFormation Stack ", !Ref "AWS::StackName" ]]


  GatewayAttachmentInternet:                       # Attachment IGW to VPC
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref GatewayInternet





#====== Public RouteTables =========
  RouteTableForPublicSubnet:                       # Creation of Empty Route Table
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value:  !Join ['-', [!Ref Environment, !Ref ClientName, !Ref Index, "publicrt", "01" ]]
      - Key: env
        Value:  !Ref Environment
      - Key: client
        Value:  !Ref ClientName
      - Key: index
        Value:  !Ref Index
      - Key: "Description"
        Value:  !Join ['', ["Created by CloudFormation Stack ", !Ref "AWS::StackName" ]]

 # Creation and Attachment of Routes for Route Table

  RoutesForPublicRouteTable:
    Type: "AWS::EC2::Route"
    DependsOn: GatewayAttachmentInternet
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref GatewayInternet
      RouteTableId: !Ref RouteTableForPublicSubnet

#====== Associate Public Route for Public Subnets
  RouteAssociationPublic01:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTableForPublicSubnet
      SubnetId: !Ref PublicSubnet01

#============ ALL Subnets ======================================================
  PublicSubnet01:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, "Fn::GetAZs": { Ref: "AWS::Region" } ]
      CidrBlock: !Ref "PublicSubnet01CIDR"
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value:  !Join ['-', [!Ref Environment, !Ref ClientName, !Ref Index, "publicsubnet", "02" ]]
      - Key: env
        Value:  !Ref Environment
      - Key: client
        Value:  !Ref ClientName
      - Key: index
        Value:  !Ref Index
      - Key: "Description"
        Value:  !Join ['', ["Created by CloudFormation Stack ", !Ref "AWS::StackName" ]]


#=================== OUTPUTS ===========================
Outputs:
  VPC:
    Description: ID for the VPC
    Value: !Ref VPC
    Export:
      Name: !Join ['-', [!Ref Environment, !Ref ClientName, !Ref Index, "vpc", "01" ]]

  VPCBlock:
    Description: Primary CIDR block for the VPC
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Join ['-', [!Ref Environment, !Ref ClientName, !Ref Index, "cidr", "01" ]]

  PublicSubnet01:
    Description: ID for Public Subnet 01
    Value: !Ref PublicSubnet01
    Export:
      Name: !Join ['-', [!Ref Environment, !Ref ClientName, !Ref Index, "publicsubnet", "01" ]]
